import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt;

import '../constants/app_constants.dart';
import '../database/hive_boxes.dart';
import '../utils/subtitle_parser.dart';
import 'yt_log.dart';

class YoutubeSearchResult {
  final String videoId;
  final String title;
  final String author;
  final String thumbnailUrl;
  final int durationMs;

  const YoutubeSearchResult({
    required this.videoId,
    required this.title,
    required this.author,
    required this.thumbnailUrl,
    required this.durationMs,
  });
}

class YoutubeQualityOption {
  final String label;
  final String url;
  final String? audioUrl;
  final int bitsPerSecond;

  const YoutubeQualityOption({
    required this.label,
    required this.url,
    this.audioUrl,
    required this.bitsPerSecond,
  });
}

class YoutubeStream {
  final String videoUrl;
  final String? audioUrl;
  final String label;

  const YoutubeStream({required this.videoUrl, this.audioUrl, required this.label});
}

class YoutubeCaptionTrack {
  final String languageCode;
  final String languageName;
  final bool autoGenerated;

  const YoutubeCaptionTrack({
    required this.languageCode,
    required this.languageName,
    required this.autoGenerated,
  });
}

class YoutubeDownloadOption {
  final String label;
  final bool audioOnly;
  final String? videoUrl;
  final String audioUrl;

  final int videoBytes;
  final int audioBytes;

  /// Request headers the URLs above were signed/authorized for. Null means
  /// "use the legacy per-client headers from [YoutubeService.streamHeadersFor]"
  /// — set for options resolved via the native yt-dlp path
  /// ([YoutubeNativeDownloadResolver]), where yt-dlp itself decides which
  /// headers the URL needs and they must be sent back exactly as given.
  final Map<String, String>? headers;

  /// yt-dlp's own `-f` selector string that produced this option, e.g.
  /// `"bestvideo[height<=720]+bestaudio/best[height<=720]"`. Null for
  /// options from the legacy youtube_explode_dart path. Stored so a later
  /// retry can re-resolve fresh URLs the same way instead of falling back
  /// to the old manifest-based refresh.
  final String? nativeFormatSelector;

  const YoutubeDownloadOption({
    required this.label,
    required this.audioOnly,
    required this.audioUrl,
    this.videoUrl,
    this.videoBytes = 0,
    this.audioBytes = 0,
    this.headers,
    this.nativeFormatSelector,
  });

  int get totalBytes => videoBytes + audioBytes;
  String get extension => audioOnly ? 'm4a' : 'mp4';

  String get readableSize {
    final bytes = totalBytes;
    if (bytes <= 0) return '';
    if (bytes >= 1024 * 1024 * 1024) {
      return '${(bytes / (1024 * 1024 * 1024)).toStringAsFixed(2)} GB';
    }
    return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
  }
}

const String kYoutubeUserAgent =
    'com.google.android.apps.youtube.vr.oculus/1.56.21 (Linux; U; Android 12; en_US; Quest 3 Build/SQ3A.220605.009.A1) gzip';

const Map<String, String> kYoutubeStreamHttpHeaders = {
  'user-agent': kYoutubeUserAgent,
};

class _YtClientProfile {
  final String name;
  final yt.YoutubeApiClient client;
  final String userAgent;

  const _YtClientProfile(this.name, this.client, this.userAgent);

  Map<String, String> get headers => {'user-agent': userAgent};
}

/// A successful resolve, returned by [YoutubeService._tryClient] *without*
/// touching any shared per-video state. Profiles are now tried concurrently,
/// so the loser of a race must not be able to overwrite `_profileFor` (and
/// therefore the User-Agent mpv is handed) behind the winner's back — only
/// the caller commits, via `_commit`.
class _Resolved {
  final YoutubeStream stream;
  final _YtClientProfile profile;
  final yt.StreamManifest manifest;
  final bool adaptive;

  /// Best muxed (progressive) URL from the *same* manifest, worked out at
  /// resolve time and kept on hand. When mpv rejects the adaptive pair, the
  /// fallback is then already in memory — previously that path went and
  /// fetched a whole second manifest plus a fresh round of probes, which is
  /// the bulk of the delay you see between tapping a video and it playing.
  final String? preparedFallbackUrl;

  const _Resolved(
    this.stream,
    this.profile,
    this.manifest,
    this.adaptive, {
    this.preparedFallbackUrl,
  });
}

/// googlevideo URLs carry an `expire` query param roughly 6h out, but they
/// start 403-ing well before that once the session that minted them goes
/// stale. Two hours is comfortably inside that window.
const Duration _kStreamCacheTtl = Duration(hours: 2);

class _CachedStream {
  final Future<YoutubeStream> future;
  final DateTime createdAt;

  _CachedStream(this.future) : createdAt = DateTime.now();

  bool get isStale => DateTime.now().difference(createdAt) > _kStreamCacheTtl;
}

class YoutubeService {
  yt.YoutubeExplode? _client;

  yt.YoutubeExplode get _yt => _client ??= yt.YoutubeExplode();

  /// Preference order. `androidSdkless` leads because it is the client that
  /// actually survives YouTube's current bot checks — `androidVr` reliably
  /// answers "Sign in to confirm you're not a bot" and `ios` hands back URLs
  /// that 403 on first byte, so having them first meant every single playback
  /// paid two dead network rounds before reaching a working client.
  static final List<_YtClientProfile> _clientProfiles = [
    _YtClientProfile(
      'androidSdkless',
      yt.YoutubeApiClient.androidSdkless,
      'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip',
    ),
    _YtClientProfile(
      'ios',
      yt.YoutubeApiClient.ios,
      'com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)',
    ),
    _YtClientProfile(
      'androidVr',
      yt.YoutubeApiClient.androidVr,
      'com.google.android.apps.youtube.vr.oculus/1.56.21 (Linux; U; Android 12; en_US; Quest 3 Build/SQ3A.220605.009.A1) gzip',
    ),
    _YtClientProfile(
      'mediaConnect',
      yt.YoutubeApiClient.mediaConnect,
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    ),
    _YtClientProfile(
      'tv',
      yt.YoutubeApiClient.tv,
      'Mozilla/5.0 (ChromiumStylePlatform) Cobalt/Version',
    ),
    _YtClientProfile(
      'mweb',
      yt.YoutubeApiClient.mweb,
      'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36',
    ),
  ];

  final Map<String, List<YoutubeSearchResult>> _searchCache = {};
  final Map<String, _CachedStream> _streamCache = {};

  final Map<String, Future<yt.StreamManifest>> _manifestCache = {};
  final Map<String, Future<yt.ClosedCaptionManifest>> _captionManifestCache = {};

  final Map<String, _YtClientProfile> _profileFor = {};
  final Map<String, bool> _adaptiveAuthorized = {};

  /// Name of the profile that last resolved anything successfully, restored
  /// from Hive on first use. YouTube's client blocking moves in waves, so
  /// whatever worked five minutes ago is overwhelmingly likely to work now.
  String? _lastGoodProfile;
  bool _lastGoodProfileLoaded = false;

  /// One shared client for all playability probes. Building a fresh
  /// [HttpClient] per probe (as this used to) forced a full TLS handshake
  /// every time — several hundred ms each, on every attempt, for nothing.
  static final HttpClient _probeClient = HttpClient()
    ..connectionTimeout = const Duration(seconds: 4)
    ..idleTimeout = const Duration(seconds: 30);

  String? get _rememberedProfile {
    if (!_lastGoodProfileLoaded) {
      _lastGoodProfileLoaded = true;
      try {
        _lastGoodProfile =
            Hive.box(HiveBoxes.appSettings).get(AppConstants.keyYtLastGoodProfile) as String?;
      } catch (_) {
        // Box not open (tests, isolates) — just fall back to static order.
      }
    }
    return _lastGoodProfile;
  }

  void _rememberProfile(String name) {
    _lastGoodProfileLoaded = true;
    if (_lastGoodProfile == name) return;
    _lastGoodProfile = name;
    try {
      Hive.box(HiveBoxes.appSettings).put(AppConstants.keyYtLastGoodProfile, name);
    } catch (_) {}
  }

  /// [_clientProfiles], with the remembered winner hoisted to the front.
  List<_YtClientProfile> _orderedProfiles() {
    final name = _rememberedProfile;
    if (name == null) return _clientProfiles;
    return [
      ..._clientProfiles.where((p) => p.name == name),
      ..._clientProfiles.where((p) => p.name != name),
    ];
  }

  final Map<String, String> _preparedFallback = {};
  final Set<String> _preparedFallbackUsed = {};

  void _commit(String videoId, _Resolved r) {
    _profileFor[videoId] = r.profile;
    _adaptiveAuthorized[videoId] = r.adaptive;
    _manifestCache[videoId] = Future.value(r.manifest);
    _preparedFallbackUsed.remove(videoId);
    final fallback = r.preparedFallbackUrl;
    if (fallback != null) {
      _preparedFallback[videoId] = fallback;
    } else {
      _preparedFallback.remove(videoId);
    }
    _rememberProfile(r.profile.name);
  }

  String userAgentFor(String videoId) =>
      _profileFor[videoId]?.userAgent ?? kYoutubeUserAgent;

  Map<String, String> streamHeadersFor(String videoId) =>
      _profileFor[videoId]?.headers ?? kYoutubeStreamHttpHeaders;

  /// Last-resort progressive (muxed) URL: a single file that carries both
  /// video and audio, so mpv never needs a secondary audio stream (and the
  /// per-stream header plumbing that goes with it).
  Future<String?> muxedFallbackUrl(String videoId) async {
    // Fast path: the resolve already picked a progressive URL out of the same
    // manifest. Hand it straight back — no manifest fetch, no probe.
    final prepared = _preparedFallback[videoId];
    if (prepared != null && _preparedFallbackUsed.add(videoId)) {
      _adaptiveAuthorized[videoId] = false;
      debugPrint('[youtube] using prepared muxed fallback for $videoId');
      return prepared;
    }

    // Slow path: the prepared URL was already tried and mpv rejected that too,
    // so go and find a working client from scratch — with probes this time.
    final current = _profileFor[videoId];
    for (final profile in [
      if (current != null) current,
      ..._orderedProfiles().where((p) => p.name != current?.name),
    ]) {
      try {
        final manifest = await _yt.videos.streamsClient.getManifest(
          videoId,
          ytClients: [profile.client],
        );
        final stream = await _firstPlayableMuxed(manifest, profile.headers);
        if (stream != null) {
          _profileFor[videoId] = profile;
          _adaptiveAuthorized[videoId] = false;
          _manifestCache[videoId] = Future.value(manifest);
          _rememberProfile(profile.name);
          debugPrint('[youtube] ${profile.name}: muxed fallback ok for $videoId');
          return stream.url.toString();
        }
      } catch (e) {
        debugPrint('[youtube] ${profile.name}: muxed fallback failed for $videoId — $e');
      }
    }
    return null;
  }

  /// Probes at most [limit] muxed variants, all at once. The old code walked
  /// *every* variant serially at an 8s timeout apiece, which on a bad video
  /// could burn 30s+ on its own before the next client was even tried.
  Future<yt.MuxedStreamInfo?> _firstPlayableMuxed(
    yt.StreamManifest manifest,
    Map<String, String> headers, {
    int limit = 2,
  }) async {
    final muxed = manifest.muxed.toList()
      ..sort((a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond));
    final candidates = muxed.take(limit).toList();
    if (candidates.isEmpty) return null;
    final results = await Future.wait(
      candidates.map((s) => _isPlayable(s.url.toString(), headers)),
    );
    for (var i = 0; i < candidates.length; i++) {
      if (results[i]) return candidates[i];
    }
    return null;
  }

  /// Fetches the manifest for one specific client, cached per (video, client).
  Future<yt.StreamManifest?> _manifestForProfile(
    String videoId,
    _YtClientProfile profile,
  ) async {
    final key = '$videoId::${profile.name}';
    final cached = _profileManifestCache[key];
    if (cached != null) return cached;
    // Negative results are cached too. Without this, every menu open re-tried
    // the clients that are currently blocked — androidVr answering the bot
    // check, mediaConnect 403-ing the player endpoint — and paid full network
    // latency for each of them again. That repetition, not the successful
    // fetch, is what made the quality and download panels slow to appear.
    if (_profileManifestFailed.contains(key)) return null;
    try {
      final manifest = await _yt.videos.streamsClient
          .getManifest(videoId, ytClients: [profile.client])
          // A client that hangs must not be able to hold the menu open. Ten
          // rather than six seconds: these run while a video is streaming, so
          // the connection is already busy and six was firing on clients that
          // were only slow — including, in one log, androidSdkless, the very
          // client that was working, which then stayed blacklisted.
          .timeout(const Duration(seconds: 10));
      _profileManifestCache[key] = manifest;
      return manifest;
    } catch (e) {
      // Only a real refusal is remembered. A timeout says nothing about
      // whether this client would work, so it must not poison the cache.
      if (e is! TimeoutException) _profileManifestFailed.add(key);
      debugPrint('[youtube] ${profile.name}: manifest unavailable for $videoId — $e');
      return null;
    }
  }

  final Map<String, yt.StreamManifest> _profileManifestCache = {};
  final Set<String> _profileManifestFailed = {};

  /// Which client turned out to have the tallest format ladder for a video.
  /// Deliberately only a name: it holds no URLs, so it stays valid after the
  /// URLs expire and survives [_invalidate]. That is what stops the probing
  /// from re-running every time a menu is opened.
  final Map<String, String> _bestLadderProfile = {};

  _YtClientProfile? _profileNamed(String name) {
    for (final p in _clientProfiles) {
      if (p.name == name) return p;
    }
    return null;
  }

  /// Works the quality ladder out ahead of time so the menu opens from cache.
  /// Safe to call repeatedly and safe to leave unawaited.
  Future<void> prefetchQualityLadder(String videoId) async {
    try {
      await _upgradeToRichestManifest(videoId);
    } catch (e) {
      debugPrint('[youtube] ladder prefetch failed for $videoId — $e');
    }
  }

  int _ladderTop(yt.StreamManifest m) => m.videoOnly.isEmpty
      ? 0
      : m.videoOnly.map((s) => s.videoResolution.height).reduce((a, b) => a > b ? a : b);

  /// Re-points [videoId] at whichever client exposes the richest format ladder.
  ///
  /// The format list is per-client, not per-video: the same upload can offer a
  /// full 144p–1080p ladder to one client and nothing above 360p to another.
  /// Playback resolve deliberately takes the *first* client that answers,
  /// because it is on the critical path — but that client is not necessarily
  /// the one with the most formats, and its manifest is what got cached. That
  /// is why the quality menu and the download list could both collapse to a
  /// single 360p entry on some videos while others showed the full ladder.
  ///
  /// Opening a quality or download menu is a deliberate user action, so
  /// spending a few parallel manifest fetches here is worth it. Only the
  /// winner's profile is adopted, so the User-Agent stays consistent with the
  /// URLs handed to mpv and to the downloader.
  Future<void> _upgradeToRichestManifest(String videoId) async {
    // Fast path: already worked out for this video. Adopting the winner costs
    // at most one manifest fetch and usually zero, because it is still cached.
    // This is what makes every menu open after the first one instant, and it
    // also survives getDownloadOptions calling _invalidate to refresh URLs.
    final known = _bestLadderProfile[videoId];
    if (known != null) {
      if (_profileFor[videoId]?.name == known) return;
      final profile = _profileNamed(known);
      if (profile == null) return;
      final manifest = await _manifestForProfile(videoId, profile);
      if (manifest == null) return;
      _adoptProfile(videoId, profile, manifest);
      return;
    }

    final current = _profileFor[videoId];
    // Four is enough to cover the clients that behave differently here; going
    // wider just adds round trips for profiles that never win.
    final candidates = _orderedProfiles()
        .where((p) => !_profileManifestFailed.contains('$videoId::${p.name}'))
        .take(3)
        .toList();
    if (candidates.isEmpty) return;

    final fetched = await Future.wait(
      candidates.map((p) async {
        final m = await _manifestForProfile(videoId, p);
        return m == null ? null : MapEntry(p, m);
      }),
    );

    // Baseline is whatever the client currently in use can offer, taken from
    // this same batch so no extra fetch is needed.
    var bestTop = -1;
    for (final entry in fetched) {
      if (entry != null && entry.key.name == current?.name) {
        bestTop = _ladderTop(entry.value);
      }
    }

    MapEntry<_YtClientProfile, yt.StreamManifest>? best;
    for (final entry in fetched) {
      if (entry == null) continue;
      final top = _ladderTop(entry.value);
      // Strictly better only — a tie keeps the client already in use, whose
      // URLs are the ones currently playing.
      if (top > bestTop) {
        bestTop = top;
        best = entry;
      }
    }

    if (best == null) {
      // Nothing beat the client already in use — record that, so this probing
      // never runs again for this video.
      if (current != null) _bestLadderProfile[videoId] = current.name;
      return;
    }
    _bestLadderProfile[videoId] = best.key.name;
    debugPrint(
      '[youtube] ${best.key.name} offers a taller ladder (${bestTop}p) for $videoId'
      '${current == null ? '' : ' than ${current.name}'}',
    );
    _adoptProfile(videoId, best.key, best.value);
  }

  /// Switches [videoId] over to [profile] and its [manifest].
  ///
  /// Clearing the prepared fallback is the important part. That URL was minted
  /// by the *previous* client, but `streamHeadersFor` returns the User-Agent
  /// of whichever client is current — so after a swap the fast fallback path
  /// would hand mpv a URL signed for one client together with another client's
  /// UA. googlevideo answers that with 403, mpv burns its second and last
  /// fallback attempt re-opening from scratch, and each re-open restarts the
  /// stream at zero. Dropping the stale URL forces the fallback to re-derive
  /// one that matches the headers it will actually be fetched with.
  void _adoptProfile(
    String videoId,
    _YtClientProfile profile,
    yt.StreamManifest manifest,
  ) {
    if (_profileFor[videoId]?.name == profile.name) return;
    _profileFor[videoId] = profile;
    _manifestCache[videoId] = Future.value(manifest);
    _preparedFallback.remove(videoId);
    _preparedFallbackUsed.remove(videoId);
    _rememberProfile(profile.name);
  }

  Future<yt.StreamManifest> _manifestFor(String videoId) {
    final cached = _manifestCache[videoId];
    if (cached != null) return cached;
    return _manifestCache.putIfAbsent(
      videoId,
      () => _yt.videos.streamsClient.getManifest(
        videoId,
        ytClients: _orderedProfiles().map((p) => p.client).toList(),
      ),
    );
  }

  Future<List<YoutubeSearchResult>> search(String query, {int limit = 25}) async {
    final trimmed = query.trim();
    if (trimmed.isEmpty) return [];

    final cached = _searchCache[trimmed];
    if (cached != null) return cached;

    final results = await _yt.search.search(trimmed);
    final out = <YoutubeSearchResult>[];
    for (final video in results) {
      if (video.isLive) continue;
      out.add(
        YoutubeSearchResult(
          videoId: video.id.value,
          title: video.title,
          author: video.author,
          thumbnailUrl: video.thumbnails.mediumResUrl,
          durationMs: video.duration?.inMilliseconds ?? 0,
        ),
      );
      if (out.length >= limit) break;
    }
    _searchCache[trimmed] = out;
    return out;
  }

  /// Picks the video-only stream for *playback*.
  ///
  /// ROOT CAUSE of the YouTube stutter, fixed here in three places:
  ///
  /// 1. maxHeight defaulted to 1080, and the sort led with height descending,
  ///    so playback always streamed the highest variant available no matter
  ///    which quality had been chosen. On a mobile connection that is a 1080p
  ///    video-only stream plus a second concurrent audio stream.
  /// 2. The "prefer mp4" tie-break does not mean H.264. AV1 (av01) ships in an
  ///    mp4 container too, so it ranked equal to avc1 and could win on bitrate.
  ///    AV1 has no hardware decoder on most Android devices, so mpv drops to
  ///    software decode — and with hwdec=auto-copy every frame is also copied
  ///    back through system memory.
  /// 3. There was no frame-rate preference, so a 720p60 variant outranked
  ///    720p30 and doubled the decode and bandwidth cost for no visible gain
  ///    on a phone.
  ///
  /// [maxHeight] now defaults to 720. Raise it if you want 1080p playback and
  /// have the bandwidth for it; the download path is unaffected either way.
  yt.VideoOnlyStreamInfo? _bestVideoOnly(yt.StreamManifest manifest, {int maxHeight = 720}) {
    final candidates = manifest.videoOnly.where((s) => s.videoResolution.height <= maxHeight).toList()
      ..sort((a, b) {
        // 1. H.264 above everything. It is the only codec with dependable
        //    hardware decoding across Android devices.
        final aAvc = a.videoCodec.toLowerCase().startsWith('avc1') ? 1 : 0;
        final bAvc = b.videoCodec.toLowerCase().startsWith('avc1') ? 1 : 0;
        final byCodec = bAvc.compareTo(aAvc);
        if (byCodec != 0) return byCodec;

        // 2. 30fps or below. A 60fps variant costs twice the decode and twice
        //    the bandwidth, which is the difference between smooth and not on
        //    a mid-range phone.
        final aStd = a.framerate.framesPerSecond <= 31 ? 1 : 0;
        final bStd = b.framerate.framesPerSecond <= 31 ? 1 : 0;
        final byFps = bStd.compareTo(aStd);
        if (byFps != 0) return byFps;

        // 3. Then the largest frame that survived the maxHeight filter.
        final byHeight = b.videoResolution.height.compareTo(a.videoResolution.height);
        if (byHeight != 0) return byHeight;

        final aMp4 = a.container == yt.StreamContainer.mp4 ? 1 : 0;
        final bMp4 = b.container == yt.StreamContainer.mp4 ? 1 : 0;
        final byContainer = bMp4.compareTo(aMp4);
        if (byContainer != 0) return byContainer;
        return b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond);
      });

    final chosen = candidates.isEmpty ? null : candidates.first;
    if (chosen != null) {
      YtLog.play(
        'format=${chosen.tag} codec=${chosen.videoCodec} '
        'resolution=${chosen.videoResolution.width}x${chosen.videoResolution.height} '
        'fps=${chosen.framerate.framesPerSecond} '
        'bitrate=${(chosen.bitrate.bitsPerSecond / 1000).round()}kbps '
        'container=${chosen.container.name}',
      );
    }
    return chosen;
  }

  yt.AudioOnlyStreamInfo? _bestAudioOnly(yt.StreamManifest manifest) {
    final candidates = manifest.audioOnly.toList()
      ..sort((a, b) {
        // AAC (mp4a) ahead of Opus, for the same hardware-decode reason as
        // the video picker. Container alone did not guarantee this.
        final aAac = a.audioCodec.toLowerCase().startsWith('mp4a') ? 1 : 0;
        final bAac = b.audioCodec.toLowerCase().startsWith('mp4a') ? 1 : 0;
        final byCodec = bAac.compareTo(aAac);
        if (byCodec != 0) return byCodec;
        final aMp4 = a.container == yt.StreamContainer.mp4 ? 1 : 0;
        final bMp4 = b.container == yt.StreamContainer.mp4 ? 1 : 0;
        final byContainer = bMp4.compareTo(aMp4);
        if (byContainer != 0) return byContainer;
        return b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond);
      });
    final chosen = candidates.isEmpty ? null : candidates.first;
    if (chosen != null) {
      YtLog.play('audio codec=${chosen.audioCodec} '
          'bitrate=${(chosen.bitrate.bitsPerSecond / 1000).round()}kbps');
    }
    return chosen;
  }

  Future<bool> _isPlayable(String url, Map<String, String> headers) async {
    try {
      final request = await _probeClient
          .getUrl(Uri.parse(url))
          .timeout(const Duration(seconds: 4));
      // Set the UA on the request, never on the shared client — probes run
      // concurrently now and would otherwise race over HttpClient.userAgent.
      headers.forEach(request.headers.set);
      request.headers.set(HttpHeaders.rangeHeader, 'bytes=0-1');
      final response = await request.close().timeout(const Duration(seconds: 4));
      await response.drain<void>();
      final ok = response.statusCode == HttpStatus.ok ||
          response.statusCode == HttpStatus.partialContent;
      if (!ok) debugPrint('[youtube] stream probe returned ${response.statusCode}');
      return ok;
    } catch (e) {
      debugPrint('[youtube] stream probe failed: $e');
      return false;
    }
  }

  /// Resolves [videoId] using a single client profile. Deliberately writes
  /// **no** shared state — see [_Resolved]. Returns null if this client can't
  /// produce anything playable.
  ///
  /// With [probe] false (the default, and what playback uses) this costs
  /// exactly one manifest fetch and returns as soon as it lands. The probes
  /// were two extra round trips that turned out not to predict anything: they
  /// happily returned 206 for URLs mpv then refused with 403, so the app paid
  /// for them *and* still took the fallback path. mpv is now the judge, and
  /// [_Resolved.preparedFallbackUrl] makes losing that judgement cheap.
  Future<_Resolved?> _tryClient(
    String videoId,
    _YtClientProfile profile, {
    bool probe = false,
  }) async {
    final yt.StreamManifest manifest;
    try {
      manifest = await _yt.videos.streamsClient.getManifest(
        videoId,
        ytClients: [profile.client],
      );
    } catch (e) {
      debugPrint('[youtube] ${profile.name}: manifest failed for $videoId — $e');
      return null;
    }

    final headers = profile.headers;

    final muxedByBitrate = manifest.muxed.toList()
      ..sort((a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond));
    final bestMuxed = muxedByBitrate.isEmpty ? null : muxedByBitrate.first;

    final bestVideo = _bestVideoOnly(manifest);
    final bestAudio = _bestAudioOnly(manifest);
    if (bestVideo != null && bestAudio != null) {
      final videoUrl = bestVideo.url.toString();
      final audioUrl = bestAudio.url.toString();
      var ok = true;
      if (probe) {
        final checks = await Future.wait([
          _isPlayable(videoUrl, headers),
          _isPlayable(audioUrl, headers),
        ]);
        ok = checks[0] && checks[1];
        if (!ok) {
          debugPrint(
            '[youtube] ${profile.name}: adaptive rejected for $videoId '
            '(video ok: ${checks[0]}, audio ok: ${checks[1]}) — trying muxed',
          );
        }
      }
      if (ok) {
        debugPrint('[youtube] ${profile.name}: adaptive ok for $videoId');
        return _Resolved(
          YoutubeStream(
            videoUrl: videoUrl,
            audioUrl: audioUrl,
            label: bestVideo.qualityLabel,
          ),
          profile,
          manifest,
          true,
          preparedFallbackUrl: bestMuxed?.url.toString(),
        );
      }
    }

    final muxedStream =
        probe ? await _firstPlayableMuxed(manifest, headers) : bestMuxed;
    if (muxedStream == null) return null;
    debugPrint('[youtube] ${profile.name}: muxed ok for $videoId');
    return _Resolved(
      YoutubeStream(
        videoUrl: muxedStream.url.toString(),
        label: muxedStream.qualityLabel,
      ),
      profile,
      manifest,
      false,
    );
  }

  static const int _waveSize = 3;

  /// Runs a wave of profiles concurrently and returns as soon as the outcome
  /// is *decided*, rather than when every member has finished.
  ///
  /// The distinction matters a lot in practice. `Future.wait` made a wave cost
  /// its slowest member, and the slowest member is reliably `ios` — which
  /// takes a full manifest fetch only to throw 403. So even once
  /// `androidSdkless` had already answered, playback sat waiting on a client
  /// whose answer could no longer change anything. Here, the moment the
  /// most-preferred profile succeeds, everyone else is abandoned mid-flight
  /// (they finish in the background and their results are dropped).
  Future<_Resolved?> _raceWave(
    String videoId,
    List<_YtClientProfile> wave, {
    required bool probe,
  }) {
    final completer = Completer<_Resolved?>();
    final results = List<_Resolved?>.filled(wave.length, null);
    final settled = List<bool>.filled(wave.length, false);

    void maybeFinish() {
      if (completer.isCompleted) return;
      for (var i = 0; i < wave.length; i++) {
        // A more-preferred profile is still running and could still win, so
        // its answer has to come in before we can commit to a lesser one.
        if (!settled[i]) return;
        if (results[i] != null) {
          completer.complete(results[i]);
          return;
        }
      }
      completer.complete(null);
    }

    for (var i = 0; i < wave.length; i++) {
      final index = i;
      _tryClient(videoId, wave[index], probe: probe).then((r) {
        results[index] = r;
        settled[index] = true;
        maybeFinish();
      }).catchError((Object e) {
        debugPrint('[youtube] ${wave[index].name}: threw for $videoId — $e');
        settled[index] = true;
        maybeFinish();
      });
    }

    return completer.future;
  }

  Future<YoutubeStream> _resolveInWaves(String videoId) async {
    final ordered = _orderedProfiles();
    // Pass 1: no probes, so a wave is just "whichever manifest arrives first".
    // Pass 2 only runs if every client failed outright, and probes so a client
    // that can only serve progressive still gets a chance.
    for (final probe in [false, true]) {
      for (var i = 0; i < ordered.length; i += _waveSize) {
        final wave = ordered.skip(i).take(_waveSize).toList();
        final r = await _raceWave(videoId, wave, probe: probe);
        if (r != null) {
          _commit(videoId, r);
          return r.stream;
        }
      }
    }
    throw StateError('No playable stream available for this video.');
  }

  Future<YoutubeStream> resolveStreamUrl(String videoId) {
    // Cached resolves expire: googlevideo URLs stop working long before the
    // app is restarted, which is what made downloads started from an
    // already-open search 403 out.
    final cached = _streamCache[videoId];
    if (cached != null && !cached.isStale) return cached.future;
    if (cached != null) _invalidate(videoId);

    final future = () async {
      try {
        return await _resolveInWaves(videoId);
      } catch (e) {
        // Clear all caches on failure so a bad state is never pinned.
        _invalidate(videoId);
        rethrow;
      }
    }();

    _streamCache[videoId] = _CachedStream(future);
    return future;
  }

  void _invalidate(String videoId) {
    _streamCache.remove(videoId);
    _manifestCache.remove(videoId);
    _adaptiveAuthorized.remove(videoId);
    _profileFor.remove(videoId);
    _preparedFallback.remove(videoId);
    _preparedFallbackUsed.remove(videoId);
    _profileManifestCache.removeWhere((k, _) => k.startsWith('$videoId::'));
    _profileManifestFailed.removeWhere((k) => k.startsWith('$videoId::'));
    // _bestLadderProfile is intentionally kept: it names a client, holds no
    // URLs, and re-deriving it is exactly the work that made the menus slow.
  }

  Future<void> _ensureResolved(String videoId) async {
    if (_profileFor.containsKey(videoId)) return;
    try {
      await resolveStreamUrl(videoId);
    } catch (_) {}
  }

  Future<List<YoutubeQualityOption>> getQualityOptions(String videoId) async {
    await _ensureResolved(videoId);
    await _upgradeToRichestManifest(videoId);
    final manifest = await _manifestFor(videoId);
    final bestAudio = _bestAudioOnly(manifest);
    final audioUrl = bestAudio?.url.toString();

    // NOTE: `_adaptiveAuthorized` is deliberately *not* consulted here.
    //
    // It used to gate this list, so the moment mpv rejected an adaptive pair
    // and the muxed fallback kicked in, every higher resolution vanished from
    // the quality menu for the rest of the session — and since YouTube only
    // publishes 360p as a progressive stream any more, the menu collapsed to a
    // single 360p entry with no way back up.
    //
    // That flag is a hint about what to *auto-select*, not a statement about
    // what the user is allowed to ask for. Picking a quality goes through
    // switchRemoteQuality, which tears the player down and opens the stream
    // fresh, so an adaptive pair genuinely can work on the second attempt.
    final videoOnly = manifest.videoOnly.toList()
      ..sort((a, b) => b.videoResolution.height.compareTo(a.videoResolution.height));

    final seen = <String>{};
    final out = <YoutubeQualityOption>[];
    for (final s in videoOnly) {
      if (audioUrl == null) break;
      final label = s.qualityLabel;
      if (!seen.add(label)) continue;
      out.add(YoutubeQualityOption(
        label: label,
        url: s.url.toString(),
        audioUrl: audioUrl,
        bitsPerSecond: s.bitrate.bitsPerSecond,
      ));
    }

    // Progressive variants are always appended, not used only as a last
    // resort: when adaptive is failing, a muxed entry is the one that will
    // actually play, so the user needs it available alongside the rest.
    final muxed = manifest.muxed.toList()
      ..sort((a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond));
    for (final s in muxed) {
      final label = seen.contains(s.qualityLabel)
          ? '${s.qualityLabel} (progressive)'
          : s.qualityLabel;
      if (!seen.add(label)) continue;
      out.add(YoutubeQualityOption(
        label: label,
        url: s.url.toString(),
        bitsPerSecond: s.bitrate.bitsPerSecond,
      ));
    }
    return out;
  }

  Future<List<YoutubeDownloadOption>> getDownloadOptions(String videoId) async {
    // Force a fresh resolve — downloads are especially sensitive to expired
    // URLs, and dropping only _profileFor left the cached stream future in
    // place, so _ensureResolved returned instantly without re-committing the
    // profile and the manifest was then refetched against all six clients.
    _invalidate(videoId);
    await _ensureResolved(videoId);
    await _upgradeToRichestManifest(videoId);

    final manifest = await _manifestFor(videoId);

    final audioCandidates = manifest.audioOnly
        .where((s) => s.container == yt.StreamContainer.mp4)
        .toList()
      ..sort((a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond));

    final out = <YoutubeDownloadOption>[];

    if (audioCandidates.isNotEmpty) {
      final bestAudio = audioCandidates.first;

      final videoCandidates = manifest.videoOnly
          .where((s) => s.container == yt.StreamContainer.mp4)
          .toList()
        ..sort((a, b) {
          final byHeight = b.videoResolution.height.compareTo(a.videoResolution.height);
          if (byHeight != 0) return byHeight;
          return b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond);
        });

      final seenLabels = <String>{};
      for (final stream in videoCandidates) {
        if (!seenLabels.add(stream.qualityLabel)) continue;
        out.add(YoutubeDownloadOption(
          label: stream.qualityLabel,
          audioOnly: false,
          videoUrl: stream.url.toString(),
          audioUrl: bestAudio.url.toString(),
          videoBytes: stream.size.totalBytes,
          audioBytes: bestAudio.size.totalBytes,
        ));
      }

      final seenBitrates = <int>{};
      for (final stream in audioCandidates) {
        final kbps = stream.bitrate.kiloBitsPerSecond.round();
        if (!seenBitrates.add(kbps)) continue;
        out.add(YoutubeDownloadOption(
          label: '$kbps kbps',
          audioOnly: true,
          audioUrl: stream.url.toString(),
          audioBytes: stream.size.totalBytes,
        ));
      }
    }

    // Progressive variants are always listed, not kept as a last resort.
    // Adaptive (video-only + audio-only) URLs are the ones YouTube currently
    // refuses with 403, so if the adaptive entries are the only thing offered
    // there is no quality the user can actually download. A muxed stream is a
    // single already-combined file, needs no mux step, and is served from the
    // same URLs playback successfully falls back to.
    final muxedLabels = <String>{};
    for (final stream in manifest.muxed) {
      if (stream.container != yt.StreamContainer.mp4) continue;
      if (!muxedLabels.add(stream.qualityLabel)) continue;
      out.add(YoutubeDownloadOption(
        label: out.isEmpty
            ? stream.qualityLabel
            : '${stream.qualityLabel} (progressive)',
        audioOnly: false,
        audioUrl: stream.url.toString(),
        audioBytes: stream.size.totalBytes,
      ));
    }

    return out;
  }

  /// The best single-file (muxed) option for [videoId], or null if the video
  /// has no progressive stream. Used as the download's last resort when the
  /// adaptive URLs keep coming back 403 even after a refresh.
  Future<YoutubeDownloadOption?> progressiveDownloadOption(String videoId) async {
    final manifest = await _manifestFor(videoId);
    final muxed = manifest.muxed
        .where((s) => s.container == yt.StreamContainer.mp4)
        .toList()
      ..sort((a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond));
    if (muxed.isEmpty) return null;
    final best = muxed.first;
    return YoutubeDownloadOption(
      label: best.qualityLabel,
      audioOnly: false,
      audioUrl: best.url.toString(),
      audioBytes: best.size.totalBytes,
    );
  }

  Future<yt.ClosedCaptionManifest> _captionManifestFor(String videoId) {
    return _captionManifestCache.putIfAbsent(videoId, () => _yt.videos.closedCaptions.getManifest(videoId));
  }

  Future<List<YoutubeCaptionTrack>> getCaptionTracks(String videoId) async {
    try {
      final manifest = await _captionManifestFor(videoId);
      return manifest.tracks
          .map((t) => YoutubeCaptionTrack(
                languageCode: t.language.code,
                languageName: t.language.name,
                autoGenerated: t.isAutoGenerated,
              ))
          .toList();
    } catch (_) {
      _captionManifestCache.remove(videoId);
      return [];
    }
  }

  Future<List<SubtitleCue>> getCaptionCues(String videoId, String languageCode) async {
    final manifest = await _captionManifestFor(videoId);
    final trackInfo = manifest.tracks.firstWhere(
      (t) => t.language.code == languageCode,
      orElse: () => manifest.tracks.first,
    );
    final track = await _yt.videos.closedCaptions.get(trackInfo);
    return track.captions
        .map((c) => SubtitleCue(start: c.offset, end: c.offset + c.duration, text: c.text))
        .toList();
  }

  void prefetchStream(String videoId) {
    unawaited(resolveStreamUrl(videoId).catchError((_) => const YoutubeStream(videoUrl: '', label: '')));
  }

  void dispose() {
    _client?.close();
    _client = null;
  }
}