import 'package:flutter/material.dart';

import '../../../core/services/youtube_service.dart';
import '../../../core/theme/app_theme.dart';

/// Quality picker for a YouTube stream. Returns the chosen option, or null
/// if the sheet was dismissed without a selection.
Future<YoutubeQualityOption?> showQualitySheet(
  BuildContext context,
  List<YoutubeQualityOption> options,
  String? currentLabel,
) {
  final palette = Theme.of(context).extension<PrismPalette>()!;
  return showModalBottomSheet<YoutubeQualityOption>(
    context: context,
    backgroundColor: palette.surfaceElevated,
    shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(24))),
    builder: (context) => SafeArea(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.all(20),
            child: Text('Quality', style: TextStyle(color: palette.textPrimary, fontWeight: FontWeight.w700, fontSize: 16)),
          ),
          if (options.isEmpty)
            Padding(
              padding: const EdgeInsets.only(bottom: 20),
              child: Text('No alternate qualities found for this video.', style: TextStyle(color: palette.textMuted)),
            )
          else
            for (final option in options)
              RadioListTile<String>(
                value: option.label,
                groupValue: currentLabel,
                title: Text(option.label),
                subtitle: Text('${(option.bitsPerSecond / 1000).round()} kbps', style: TextStyle(color: palette.textMuted)),
                activeColor: palette.accent,
                onChanged: (_) => Navigator.pop(context, option),
              ),
          const SizedBox(height: 8),
        ],
      ),
    ),
  );
}

/// Result of the caption-language sheet: either a language pick, or the
/// sentinel "off" selection. Using a dedicated result type (rather than a
/// nullable string) keeps "user dismissed the sheet" distinguishable from
/// "user explicitly chose Off".
class CaptionSelection {
  final String? languageCode;
  const CaptionSelection.off() : languageCode = null;
  const CaptionSelection.language(this.languageCode);
  bool get isOff => languageCode == null;
}

Future<CaptionSelection?> showCaptionLanguageSheet(
  BuildContext context,
  List<YoutubeCaptionTrack> tracks,
  String? currentLanguageCode,
) {
  final palette = Theme.of(context).extension<PrismPalette>()!;
  return showModalBottomSheet<CaptionSelection>(
    context: context,
    backgroundColor: palette.surfaceElevated,
    shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(24))),
    builder: (context) => SafeArea(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.all(20),
            child: Text('Subtitles/CC', style: TextStyle(color: palette.textPrimary, fontWeight: FontWeight.w700, fontSize: 16)),
          ),
          RadioListTile<String?>(
            value: null,
            groupValue: currentLanguageCode,
            title: const Text('Off'),
            activeColor: palette.accent,
            onChanged: (_) => Navigator.pop(context, const CaptionSelection.off()),
          ),
          if (tracks.isEmpty)
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
              child: Text('No captions available for this video.', style: TextStyle(color: palette.textMuted)),
            )
          else
            for (final track in tracks)
              RadioListTile<String?>(
                value: track.languageCode,
                groupValue: currentLanguageCode,
                title: Text(track.languageName),
                subtitle: track.autoGenerated ? Text('Auto-generated', style: TextStyle(color: palette.textMuted)) : null,
                activeColor: palette.accent,
                onChanged: (_) => Navigator.pop(context, CaptionSelection.language(track.languageCode)),
              ),
          const SizedBox(height: 8),
        ],
      ),
    ),
  );
}
